### PR TITLE
about group 8

### PR DESCRIPTION
**Pull request by aysuahmadli**
Aysu worked on some code

### CODE REVIEW

**Comment by emuratalieva** [comment]
great job !

**Comment by aysuahmadli** [comment]
> great job !

Thank you!

**Comment by inesa7** [comment]
awesome code

**Review by Tinbite1 — APPROVED** [review]
Awsome!

**Review by aysuahmadli — COMMENTED** [review]
completed

**Review by inesa7 — APPROVED** [review]
nice work

**Pull request merged**
